name: darty
description: A comprehensive Dart package providing utility functions, extensions, and new data structures.
version: 1.0.0
repository: https://github.com/Avijitbera/darty

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
# dependencies:
# path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
